### ISSUE TITLE
matro does not start

### ISSUE THREAD

**Issue by GauravSaini75** [CodeBrewLabs7/BrewRNKit#6]
![Screenshot 2024-04-12 at 7 42 40 PM](https://github.com/CodeBrewLabs7/BrewRNKit/assets/96723744/4d0e15e0-982e-4a5a-bf67-943ffcd79344)

**Comment by GauravSaini75** [comment]
current node version => v18.19.1

**Comment by gulsher7** [comment]
it's seem node environment  issue. Delete your .xcode.env.local file and re-install pod
